"""Delete image from models

Revision ID: 15d026a3bb93
Revises: 31222ab8533b
Create Date: 2025-02-04 16:33:24.254113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d026a3bb93'
down_revision: Union[str, None] = '31222ab8533b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employer', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('employer', 'image')
    op.drop_column('location', 'image')
    op.drop_column('residents', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residents', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('location', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('employer', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('employer', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
