"""Change location model

Revision ID: 31222ab8533b
Revises: b74ef05864d8
Create Date: 2025-01-31 06:24:08.591965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31222ab8533b'
down_revision: Union[str, None] = 'b74ef05864d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'name')
    # ### end Alembic commands ###
