"""Update employer model3

Revision ID: 92a9df00ffcb
Revises: 2776d993a6fb
Create Date: 2025-01-06 03:06:43.167705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a9df00ffcb'
down_revision: Union[str, None] = '2776d993a6fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employer_in_work_day',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_time', sa.DateTime(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employer_in_work_day')
    op.drop_table('events')
    # ### end Alembic commands ###
