"""Switch product to card

Revision ID: 98d724ece3b7
Revises: b05ac9c22d07
Create Date: 2025-03-07 21:51:13.946473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98d724ece3b7'
down_revision: Union[str, None] = 'b05ac9c22d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('link_to_download', sa.String(), nullable=False))
    op.drop_constraint('products_location_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'type_product')
    op.drop_column('products', 'components')
    op.drop_column('products', 'description')
    op.drop_column('products', 'location_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('components', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('type_product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_location_id_fkey', 'products', 'location', ['location_id'], ['id'])
    op.drop_column('products', 'link_to_download')
    # ### end Alembic commands ###
