"""Add location name in models

Revision ID: a36031124d40
Revises: 15d026a3bb93
Create Date: 2025-02-07 23:56:14.683856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36031124d40'
down_revision: Union[str, None] = '15d026a3bb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['name'])
    op.add_column('employer', sa.Column('location_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'employer', 'location', ['location_name'], ['name'])
    op.drop_column('employer', 'location_id')
    op.add_column('events', sa.Column('location_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'location', ['location_name'], ['name'])
    op.create_unique_constraint(None, 'location', ['name'])
    op.add_column('products', sa.Column('location_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'products', 'location', ['location_name'], ['name'])
    op.add_column('residents', sa.Column('location_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'residents', 'location', ['location_name'], ['name'])
    op.add_column('workdays', sa.Column('location_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'workdays', 'location', ['location_name'], ['name'])
    op.drop_column('workdays', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    op.add_column('workdays', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workdays', type_='foreignkey')
    op.drop_column('workdays', 'location_name')
    op.drop_constraint(None, 'residents', type_='foreignkey')
    op.drop_column('residents', 'location_name')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'location_name')
    op.drop_constraint(None, 'location', type_='unique')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'location_name')
    op.add_column('employer', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employer', type_='foreignkey')
    op.drop_column('employer', 'location_name')
    # ### end Alembic commands ###
