"""Change event model

Revision ID: b74ef05864d8
Revises: d7723ecffdd2
Create Date: 2025-01-31 04:54:52.741550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b74ef05864d8'
down_revision: Union[str, None] = 'd7723ecffdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workdays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_time', sa.DateTime(), nullable=False),
    sa.Column('employer_fio', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employer_fio'], ['employer.fio'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employer_in_work_day')
    op.add_column('events', sa.Column('date_start', sa.DateTime(), nullable=False))
    op.drop_column('events', 'start')
    op.drop_column('events', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('day', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('events', 'date_start')
    op.create_table('employer_in_work_day',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employer_fio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employer_fio'], ['employer.fio'], name='employer_in_work_day_employer_fio_fkey'),
    sa.PrimaryKeyConstraint('id', name='employer_in_work_day_pkey')
    )
    op.drop_table('workdays')
    # ### end Alembic commands ###
