"""Add foreing key 

Revision ID: cc3fb41c44b4
Revises: d65515d1f98a
Create Date: 2025-01-27 23:04:18.854321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3fb41c44b4'
down_revision: Union[str, None] = 'd65515d1f98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employer', ['fio'])
    op.alter_column('employer_in_work_day', 'employer_fio',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'employer_in_work_day', 'employer', ['employer_fio'], ['fio'])
    op.alter_column('events', 'day',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'day',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'employer_in_work_day', type_='foreignkey')
    op.alter_column('employer_in_work_day', 'employer_fio',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'employer', type_='unique')
    # ### end Alembic commands ###
