"""restore card

Revision ID: eb5016639266
Revises: 82c44339957f
Create Date: 2025-03-07 22:16:30.603286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5016639266'
down_revision: Union[str, None] = '82c44339957f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('description', sa.String(), nullable=False))
    op.add_column('cards', sa.Column('category', sa.String(), nullable=False))
    op.add_column('cards', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cards', 'location', ['location_id'], ['id'])
    op.drop_column('cards', 'link_to_download')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('link_to_download', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'location_id')
    op.drop_column('cards', 'category')
    op.drop_column('cards', 'description')
    # ### end Alembic commands ###
